// Language Data
export const languageList = [
  "Arabic-ar",
  "German-de",
  "English-en",
  "Spanish-es",
  "French-fr",
  "Hebrew-he",
  "Italian-it",
  "Dutch-nl",
  "Norwegian-no",
  "Portuguese-pt",
  "Russian-ru",
  "Northern Sami-se",
  "Chinese-zh",
];
// Language Data
export const countryList = [
  "UAE-ae",
  "Argentina-ar",
  "Austria-at",
  "Australia-au",
  "Belgium-be",
  "Bulgaria-bg",
  "Brazil-br",
  "Canada-ca",
  "Switzerland-ch",
  "China-cn",
  "Colombia-co",
  "Cuba-cu",
  "Czechia-cz",
  "Germany-de",
  "Egypt-eg",
  "France-fr",
  "UK-gb",
  "Greece-gr",
  "Hong Kong-hk",
  "Hungary-hu",
  "Indonesia-id",
  "Ireland-ie",
  "Israel-il",
  "India-in",
  "Italy-it",
  "Japan-jp",
  "Korea-kr",
  "Lithuania-lt",
  "Latvia-lv",
  "Morocco-ma",
  "Mexico-mx",
  "Malaysia-my",
  "Nigeria-ng",
  "Netherlands-nl",
  "Norway-no",
  "New Zealand-nz",
  "Philippines-ph",
  "Poland-pl",
  "Portugal-pt",
  "Romania-ro",
  "Serbia-rs",
  "Russian Federation-ru",
  "Saudi Arabia-sa",
  "Sweden-se",
  "Singapore-sg",
  "Slovenia-si",
  "Slovakia-sk",
  "Thailand-th",
  "Turkey-tr",
  "Taiwan-tw",
  "Ukraine-ua",
  "USA-us",
  "Venezuelave",
  "South Africa-za",
];
